### ISSUE TITLE
Binding a Dexie value to $scope variable

### ISSUE THREAD

**Issue by bobsilon** [FlussoBV/NgDexie#1]
Hello and happy new year.
I'm rookie in angular and absolutely in development :) and i found Dexie and ngDexie tonight. I worked for last week with [angular-localforage](https://github.com/ocombe/angular-localForage) which has a good property and that is binding a localforage value to a $scope variable.
I don't know Dexie's synchronous API support do the same or not, but i thought this can be good if ngDexie has something like.

Best Regards

**Comment by jwebcat** [comment]
Thanks again for your work on this. :smile_cat: 

:+1: 

I am also interested in a having a bind function added. If I get time I will try and a send a PR for this as well.

something like this: [taken from angular-locker](https://github.com/tymondesigns/angular-locker) a beautiful library to work with local and session storage for Angular

```
bind: function ($scope, key, def) {
                        if (angular.isUndefined( $scope.$eval(key) )) {
                            $parse(key).assign($scope, this.get(key, def));
                            if (! this.has(key)) this.put(key, def);
                        }

                        var self = this;
                        this._watchers[key + $scope.$id] = $scope.$watch(key, function (newVal) {
                            if (angular.isDefined(newVal)) self.put(key, newVal);
                        }, angular.isObject($scope[key]));

                        return this;
                    },
```

anyways I will probably add something to that effect as a bind function with a param for a default value if it doesn't exist in $scope already.

Thoughts?

**Comment by martindiphoorn** [comment]
Sounds like a great addition to NgDexie. Looking forward to see this in action. Please send a pull request with an example and documentation.

**Comment by martindiphoorn** [comment]
I'm already busy implementing some sort off binding to scope objects. Still having some race conditions, hope to fix them soon.
