### ISSUE TITLE
Package for npm

### ISSUE THREAD

**Issue by stephanepechard** [FlussoBV/NgDexie#10]
As a way to follow dexie movement to npm, let's make a npm package and distribute it through npmjs.org.

**Comment by stephanepechard** [comment]
Done. It was easier than expected as you already provide a `package.json` file.
It goes live here: [https://www.npmjs.com/package/ngdexie](https://www.npmjs.com/package/ngdexie)

I tested it successfully in my project. I can now remove the dependency to bower, which is a good thing.

**Comment by martindiphoorn** [comment]
This is released in version 0.0.18, thanks for the great work!

**Comment by stephanepechard** [comment]
Thanks for the new version, just published it on npm.

**Comment by craigwduckett** [comment]
@stephanepechard @martindiphoorn Would it be possible to update the version on npmjs.com, please?
