### ISSUE TITLE
Error calling ngDexie.remove

### ISSUE THREAD

**Issue by mgoku** [FlussoBV/NgDexie#12]
I tried to delete an item from table 'stock' using ngDexie.remove.

``` javascript
ngDexie.remove( 'stock', item.id ).then( function ( ) {
     console.log.('Delete item');
 });
```

The operation fail and I got error:
**TypeError: ngDexie.getDb is not a function at Object.remove (ngDexie.js:221)**

If I use 

``` javascript
ngDexie.getDb(function(db){
  db.table('stock').delete(item.id);
});
```

the operation work as expected.

I use NgDexie version 0.0.18 with Angularjs 1.5.3

**Comment by tiste** [comment]
Should be cool to solve that one...
