### ISSUE TITLE
Update dexie.js to 1.3.6

### ISSUE THREAD

**Issue by benamib** [FlussoBV/NgDexie#14]
Hi, 
Would it be possible to update `Dexie.js` to `v1.3.6` (or `1.4.0` which will soon be available) ?

**Comment by martindiphoorn** [comment]
If you want to help me out, then please install the dexie.js release you want to use before installing ngDexie. That way you will use the version you supplied. Check if everything is working alright and give the results here.

**Comment by martindiphoorn** [comment]
I already have tested this against my own application and did not saw problems. The master branch is already containing the 1.3.x version.

You can add this to your bower.json to test it:
"ng-dexie": "https://github.com/FlussoBV/NgDexie.git#master"

**Comment by benamib** [comment]
All right I'll try to update to 1.4.6 and check out the results
I'll send you a pull request if I managed to do it
