### ISSUE TITLE
[Urgent] - Integrating Dexie with angular

### ISSUE THREAD

**Issue by mbj36** [FlussoBV/NgDexie#16]
Hey @martindiphoorn  I want to use your wrapper library for my angular project https://github.com/mbj36/community-app/tree/offline 

Can u please find some time and help me how to integrate your wrapper library in my angular project :) ? 

I am having lots of issues while integrating it

**Comment by martindiphoorn** [comment]
Could you please give some more information about the things that are going wrong?

**Comment by mbj36** [comment]
I have succesfully solved it, so closing this issue!
