### ISSUE TITLE
Ability to use multiple databases?

### ISSUE THREAD

**Issue by jwebcat** [FlussoBV/NgDexie#2]
Thanks for your work on this it is awesome!!!

I'm going to add support for multiple databases through a param in each of the prototype functions. Do you want me to send a PR when it's finished?

Is this a feature others are interested in?

Thoughts?

**Comment by martindiphoorn** [comment]
This sounds like a good feature. Which probably should have been there from the beginning. So when you have added this. Please send a PR,

**Comment by martindiphoorn** [comment]
Have you ever implemented this?
