### ISSUE TITLE
Appears to require Syncable and Observable?

### ISSUE THREAD

**Issue by pauleveritt** [FlussoBV/NgDexie#3]
On this line:

https://github.com/FlussoBV/NgDexie/blob/master/dist/ngdexie.js#L95

...in init, you have "db.syncable.on". I believe this only exists if you bring in the Dexie add ons?

**Comment by martindiphoorn** [comment]
Yes you are right. I already discovered this bug in an new project last week.
I probably will push the fix below monday.

For now you could change ngdexie in this code:

```
if (db.syncable) {
  db.syncable.on('statusChanged', function (newStatus, url) {
     self.getScope().$apply(function () {
       self.getScope().$broadcast("ngDexieStatusChanged", {status: newStatus, statusText:    Dexie.Syncable.StatusTexts[newStatus], url: url});
     });
  });
}
```

Simple if fixed this.

Thanks for reporting
