### ISSUE TITLE
How to get at the .where() etc.?

### ISSUE THREAD

**Issue by pauleveritt** [FlussoBV/NgDexie#4]
I have an Angular todo clone demo app based on Dexie and ngDexie.

ngDexie puts wrappers around common Dexie operations, to put them in Angular-compliant $q wrappers. Your callback is then handed unwrapped result data. However, that cuts my queries off from the Dexie chaining of .where() and the operators.

But perhaps I'm looking at this wrong.

**Comment by pauleveritt** [comment]
BTW, my demo source is at https://github.com/pauleveritt/angular-dexie-todo and can be looked at here: http://pauleveritt.github.io/angular-dexie-todo

**Comment by martindiphoorn** [comment]
That is correct. If you want to use the advanced features off dexie you need to use the ngDexie.getDb() function in the [api](https://github.com/FlussoBV/NgDexie/wiki/ngDexie.getDb)

With getDb you can do things on the Dexie object.

**Comment by martindiphoorn** [comment]
To make the answer more complete, since the last release you can also use ngDexie.getTransaction. I'm closing this issue as i think it is answered.
