### ISSUE TITLE
Deleting items from store

### ISSUE THREAD

**Issue by frankadrian** [FlussoBV/NgDexie#5]
Is it possible to delete items in a store? 
If not why not? Is their an easier way to do it directly with dexie.js?

**Comment by martindiphoorn** [comment]
At the moment this is not possible through NgDexie.

You could do:

```
ngDexie.getDb(function(db){
  db.delete(id);
});
```

However it seems weird it is not available through ngDexie. I will leave this ticket open to implement it in the next release.

**Comment by frankadrian** [comment]
Thank you! I will try create a PR for this.

**Comment by martindiphoorn** [comment]
This function has been added in the release 0.0.15
