### ISSUE TITLE
Run angular controllers after database is open

### ISSUE THREAD

**Issue by mariowise** [FlussoBV/NgDexie#6]
Is there a way to make `angular` to wait until database is configured and open, before it runs the controllers?

**Comment by martindiphoorn** [comment]
You could use an resolve in your route definition. It will make the controller wait until it is resolved. But i never needed it yet. Can you explain why you need it?
Op 19 dec. 2015 4:06 AM schreef mariowise notifications@github.com:Is there a way to make angular to wait until database is configured and open, before it runs the controllers?
