### ISSUE TITLE
How to use Collections? 

### ISSUE THREAD

**Issue by achintverma** [FlussoBV/NgDexie#7]
Hello, thanks for the nice wrapper. I am new on Angular and Dexie both. I am trying to use database queries supported by Dexie in my controller. 

How can I use queries mentioned on this page: https://github.com/dfahlander/Dexie.js/wiki/Collection ? 

Thanks again

**Comment by martindiphoorn** [comment]
You can do this by using the db as explained here:
https://github.com/FlussoBV/NgDexie/wiki/ngDexie.getDb

**Comment by achintverma** [comment]
Hi Martin, thanks for your message. I already figured that out from your documentation. I have few suggestions to add filters for queried results. I was having a problem with composite where statements and there's no way Dexis.js collection can be ordered. It will be cool to add that feature in ngDexie. Please see this link here https://github.com/dfahlander/Dexie.js/issues/167

**Comment by martindiphoorn** [comment]
I see that the latest request was fulfilled with dexiejs. So closing this isseu.
