### ISSUE TITLE
Update compatibility to dexie version 1.2.0

### ISSUE THREAD

**Issue by stephanepechard** [FlussoBV/NgDexie#8]
Hi,
When installing NgDexie through bower, we get dexie version 1.1.0, and not [the last one](https://github.com/dfahlander/Dexie.js/releases/tag/v1.2.0). It would be great to align the wrapper against last upstream version.
Thanks!

**Comment by martindiphoorn** [comment]
You can force an other version off dexiejs by installing it with bower first (before ngDexie).

Before making ngDexie using the last version, i first need to test it. Can you please test ngDexie against the latest version off dexiejs and then report back?

**Comment by stephanepechard** [comment]
I did it by installing dexie through npm and ngDexie through bower (as it is not available through npm).
I will try to report my use, but I will quickly need production-ready material...
Thanks

**Comment by ilDon** [comment]
I can confirm that I have updated dexie to 1.2.0 and it is working as expected so far. I also have tested some of the new where clauses, and they seemed to be working fine.

**Comment by stephanepechard** [comment]
Same here, I use it in an app in production with no problem.
I will use it in another app soon, I'll keep you inform of how it behaves.

**Comment by martindiphoorn** [comment]
I just have upgrade the reference to dexie.js to version 1.2.0 as this is currently the latest version which support bower fully. Version 1.3.x addons do not have bower versions only npm.

@stephanepechard do you know a simple way to make this module npm compatible also? I don't have the time to look into it, but i think it would be a good path to take. If so could you send a pull request?

**Comment by stephanepechard** [comment]
Thanks Martin.
I will try to send you a pull request during this week. Can't promise when exactly though.
I close this issue as it is only version-related, and I open a new one for the npm packaging.
